require:
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'Gemfile'
  DisplayCopNames: true
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Standard/BlockSingleLineBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
